Repository vert-x3/vertx-web, pull requests merged in 2018-10, with the labels that each got.

#1032 Removed deprecated methods from vertx-web-api-contract
  vertx-web-api-contract/src/main/asciidoc/index.adoc
  vertx-web-api-contract/src/main/java/examples/OpenAPI3Examples.java
  vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/RouterFactory.java
  vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/impl/BaseRouterFactory.java
  vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/openapi3/OpenAPI3RouterFactory.java
  vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/openapi3/impl/OpenAPI3RouterFactoryImpl.java
Labels: ready, to review

#1034 Fixed intermittent test failure in failLoadSpecFromURL
  vertx-web-api-contract/src/test/java/io/vertx/ext/web/api/contract/openapi3/OpenAPI3RouterFactoryTest.java
Labels: to review

#1033 Updated swagger-parser to 2.0.5
  vertx-web-api-contract/pom.xml
  vertx-web-api-contract/src/test/resources/swaggers/schemas_test_spec.yaml
Labels: Planned, to review

#1035 [Web Api Contract] Add UUID validation parameter
  vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/openapi3/impl/OpenAPI3RequestValidationHandlerImpl.java
  vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/validation/ParameterType.java
  vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/validation/impl/RegularExpressions.java
  vertx-web-api-contract/src/test/java/io/vertx/ext/web/api/validation/HTTPRequestValidationTest.java
  vertx-web-api-contract/src/test/java/io/vertx/ext/web/api/validation/WebTestValidationBase.java
  vertx-web-api-contract/src/test/java/io/vertx/ext/web/api/validation/impl/StringTypeValidatorTest.java
Labels: component/api-contract/enhancement, ready

#1001 Expose openAPI model to routing context
  vertx-web-api-contract/src/main/asciidoc/dataobjects.adoc
  vertx-web-api-contract/src/main/generated/io/vertx/ext/web/api/contract/RouterFactoryOptionsConverter.java
  vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/RouterFactoryOptions.java
  vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/openapi3/impl/OpenAPI3RouterFactoryImpl.java
  vertx-web-api-contract/src/test/java/io/vertx/ext/web/api/contract/openapi3/OpenAPI3RouterFactoryTest.java
Labels: component/api-contract/enhancement, ready
