Repository vert-x3/vertx-web, pull requests merged in 2018-07, with the labels that each got.

#960 Adds only not existing cache control header values.
  vertx-web/src/main/java/io/vertx/ext/web/handler/impl/StaticHandlerImpl.java
  vertx-web/src/main/java/io/vertx/ext/web/impl/Utils.java
  vertx-web/src/test/java/io/vertx/ext/web/handler/StaticHandlerTest.java
Labels: to review

#965 Do not override CORS for SockJS
  vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/BaseTransport.java
  vertx-web/src/test/sockjs-protocol/sockjs-protocol-0.3.3.py
Labels: to review

#963 Fixed route.handler and route.failureHandler docs
  vertx-web/src/main/asciidoc/index.adoc
  vertx-web/src/main/java/examples/WebExamples.java
  vertx-web/src/main/java/io/vertx/ext/web/Route.java
Labels: to review

#968 Fixes #672
  vertx-web/src/main/java/io/vertx/ext/web/handler/impl/UserHolder.java
Labels: enhancement, to review

#882 Typo: in FormLoginHandler, the DEFAULT_RETURN_URL_PARAM comment is wrong
  vertx-web/src/main/java/io/vertx/ext/web/handler/FormLoginHandler.java
Labels: bug, to review

#914 Enable Rocker templating for Java 9
  vertx-template-engines/pom.xml
Labels: to review

#971 Typo AuthoriSation -> AuthoriZation
  vertx-web/src/main/java/io/vertx/ext/web/handler/AuthHandler.java
Labels: to review

#972 Typo autoriSation -> authoriZation
  vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/BaseTransport.java
Labels: to review

#966 Move resources under META-INF
  vertx-web/src/main/java/io/vertx/ext/web/handler/ErrorHandler.java
  vertx-web/src/main/java/io/vertx/ext/web/handler/StaticHandler.java
  vertx-web/src/main/resources/META-INF/vertx/web/vertx-web-directory.html
  vertx-web/src/main/resources/META-INF/vertx/web/vertx-web-error.html
  vertx-web/src/test/java/io/vertx/ext/web/handler/StaticHandlerTest.java
Labels: to review

#984 Add licensing information to pom.xml
  vertx-web/pom.xml
Labels: to review

#986 Fixes #943
  vertx-web/src/main/java/io/vertx/ext/web/impl/ParsableHeaderValue.java
Labels: bug

#994 Javadoc: HttpResponse bodyAs methods return null if body codec is not "Buffer"
  vertx-web-client/src/main/java/io/vertx/ext/web/client/HttpResponse.java
  vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/HttpContext.java
  vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/HttpResponseImpl.java
Labels: to review
