Repository vert-x3/vertx-web, pull requests merged in 2018-03, with the labels that each got.

#857 Avoid having method references which makes the usage cleaner IMHO
  vertx-web/src/main/asciidoc/index.adoc
  vertx-web/src/main/java/examples/WebExamples.java
  vertx-web/src/main/java/io/vertx/ext/web/Router.java
  vertx-web/src/main/java/io/vertx/ext/web/RoutingContext.java
  vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/SockJSHandlerImpl.java
  vertx-web/src/main/java/io/vertx/ext/web/impl/RouterImpl.java
  vertx-web/src/test/java/io/vertx/ext/web/RoutingContextNullCurrentRouteTest.java
  vertx-web/src/test/java/io/vertx/ext/web/WebTestBase.java
  vertx-web/src/test/java/io/vertx/ext/web/handler/StaticHandlerTest.java
  vertx-web/src/test/java/io/vertx/ext/web/handler/sockjs/SockJSTestBase.java
  vertx-web/src/test/java/io/vertx/ext/web/sstore/ClusteredSessionHandlerTest.java
Labels: enhancement, to review

#873 Revert "Add getters in HttpRequest for methd, port, host, virtualHost, uri, ssl, timeout and followRedirects"
  vertx-web-client/src/main/java/io/vertx/ext/web/client/HttpRequest.java
  vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/HttpRequestImpl.java
Labels: to review

#872 Fixed #871
  vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/openapi3/impl/OpenAPI3PathResolver.java
  vertx-web-api-contract/src/test/java/io/vertx/ext/web/api/contract/openapi3/OpenAPI3RouterFactoryTest.java
  vertx-web-api-contract/src/test/resources/swaggers/router_factory_test.yaml
Labels: to review

#880 Fix behavior for cookies on error
  vertx-web/src/main/java/io/vertx/ext/web/RoutingContext.java
  vertx-web/src/main/java/io/vertx/ext/web/handler/impl/SessionHandlerImpl.java
  vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextDecorator.java
  vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImpl.java
  vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextWrapper.java
Labels: bug, to review

#879 Update render engines dependencies
  vertx-template-engines/vertx-web-templ-freemarker/pom.xml
  vertx-template-engines/vertx-web-templ-handlebars/pom.xml
  vertx-template-engines/vertx-web-templ-jade/pom.xml
  vertx-template-engines/vertx-web-templ-mvel/pom.xml
  vertx-template-engines/vertx-web-templ-rocker/pom.xml
  vertx-web-api-contract/pom.xml
  vertx-web/pom.xml
Labels: enhancement, to review

#869 Fix #860 allow setting customised BodyHandler
  vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/RouterFactoryOptions.java
  vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/openapi3/impl/OpenAPI3RouterFactoryImpl.java
  vertx-web-api-contract/src/test/java/io/vertx/ext/web/api/contract/openapi3/OpenAPI3RouterFactoryTest.java
  vertx-web-api-contract/src/test/resources/swaggers/upload_test.yaml
Labels: component/api-contract/enhancement, to review
