Repository vert-x3/vertx-web, pull requests merged in 2019-06, with the labels that each got.

#1266 Header name from Vert.x replaced with hard coded Content-Type header …
  vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/validation/impl/BaseValidationHandler.java
Labels: to review

#1306 Adds REGISTERED hook to event bus sockjs bridge
  vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/EventBusBridgeImpl.java
  vertx-web/src/test/java/io/vertx/ext/web/handler/EventbusBridgeTest.java
Labels: enhancement

#1294 Fixes #460
  vertx-web/src/main/asciidoc/index.adoc
  vertx-web/src/main/java/examples/WebExamples.java
  vertx-web/src/main/java/io/vertx/ext/web/handler/MethodOverrideHandler.java
  vertx-web/src/main/java/io/vertx/ext/web/handler/impl/MethodOverrideHandlerImpl.java
  vertx-web/src/test/java/io/vertx/ext/web/handler/MethodOverrideHandlerTest.java
Labels: ready

#1308 Fix for Route#matches status codes
  vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImplBase.java
  vertx-web/src/test/java/io/vertx/ext/web/RouterTest.java
Labels: bug

#1291 List of followed redirects in Web Client
  vertx-web-client/src/main/java/io/vertx/ext/web/client/HttpResponse.java
  vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/HttpContext.java
  vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/HttpResponseImpl.java
  vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/predicate/PredicateInterceptor.java
  vertx-web-client/src/test/java/io/vertx/ext/web/client/InterceptorTest.java
  vertx-web-client/src/test/java/io/vertx/ext/web/client/WebClientTest.java
Labels: component/webclient

#1292 Route order fix
  vertx-web/src/main/asciidoc/index.adoc
  vertx-web/src/main/java/examples/WebExamples.java
Labels: enhancement

#1293 Cookies configured during redirects are correctly managed
  vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/ClientPhase.java
  vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/HttpContext.java
  vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/SessionAwareInterceptor.java
  vertx-web-client/src/test/java/io/vertx/ext/web/client/InterceptorTest.java
  vertx-web-client/src/test/java/io/vertx/ext/web/client/SessionAwareWebClientTest.java
Labels: component/webclient

#1302 Implemented support for custom HTTP methods in Web Client
  vertx-web-client/src/main/java/io/vertx/ext/web/client/HttpRequest.java
  vertx-web-client/src/main/java/io/vertx/ext/web/client/WebClient.java
  vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/HttpContext.java
  vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/HttpRequestImpl.java
  vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/WebClientBase.java
  vertx-web-client/src/test/java/io/vertx/ext/web/client/WebClientTest.java
Labels: enhancement

#1223 Avoid using SecureRandom directly which will block the event loop on …
  vertx-web/src/main/java/examples/WebExamples.java
  vertx-web/src/main/java/io/vertx/ext/web/handler/CSRFHandler.java
  vertx-web/src/main/java/io/vertx/ext/web/handler/impl/CSRFHandlerImpl.java
  vertx-web/src/test/java/io/vertx/ext/web/handler/CSRFHandlerTest.java
Labels: to review

#1222 Fixes: #1212
  vertx-web/src/main/java/io/vertx/ext/web/handler/DigestAuthHandler.java
  vertx-web/src/main/java/io/vertx/ext/web/handler/impl/DigestAuthHandlerImpl.java
  vertx-web/src/test/java/io/vertx/ext/web/handler/DigestAuthHandlerTest.java
Labels: to review

#1264 CSRFHandler: thrown a custom exception
  vertx-web/src/main/java/io/vertx/ext/web/handler/CSRFHandler.java
  vertx-web/src/main/java/io/vertx/ext/web/handler/impl/CSRFHandlerImpl.java
  vertx-web/src/test/java/io/vertx/ext/web/handler/CSRFHandlerTest.java
Labels: ready
