Repository vert-x3/vertx-web, pull requests merged in 2019-03, with the labels that each got.

#1190 Handle unresolved favicon path in FaviconHandler - fixes #1189 - fixe…
  vertx-web/src/main/java/io/vertx/ext/web/handler/impl/FaviconHandlerImpl.java
  vertx-web/src/main/resources/META-INF/vertx/web/favicon.ico
  vertx-web/src/test/java/io/vertx/ext/web/handler/FaviconHandlerTest.java
Labels: to review

#1194 Replacing old branch as rebase went wrong
  vertx-template-engines/vertx-web-templ-freemarker/src/test/java/io/vertx/ext/web/templ/FreeMarkerTemplateNoCacheTest.java
  vertx-template-engines/vertx-web-templ-freemarker/src/test/java/io/vertx/ext/web/templ/FreeMarkerTemplateTest.java
  vertx-template-engines/vertx-web-templ-handlebars/src/test/java/io/vertx/ext/web/templ/HandlebarsTemplateNoCacheTest.java
  vertx-template-engines/vertx-web-templ-handlebars/src/test/java/io/vertx/ext/web/templ/HandlebarsTemplateTest.java
  vertx-template-engines/vertx-web-templ-jade/src/test/java/io/vertx/ext/web/templ/JadeTemplateNoCacheTest.java
  vertx-template-engines/vertx-web-templ-jade/src/test/java/io/vertx/ext/web/templ/JadeTemplateTest.java
  vertx-template-engines/vertx-web-templ-mvel/src/test/java/io/vertx/ext/web/templ/MVELTemplateNoCacheTest.java
  vertx-template-engines/vertx-web-templ-mvel/src/test/java/io/vertx/ext/web/templ/MVELTemplateTest.java
  vertx-template-engines/vertx-web-templ-pebble/src/test/java/io/vertx/ext/web/templ/PebbleTemplateNoCacheTest.java
  vertx-template-engines/vertx-web-templ-pebble/src/test/java/io/vertx/ext/web/templ/PebbleTemplateTest.java
  vertx-template-engines/vertx-web-templ-thymeleaf/src/main/java/io/vertx/ext/web/templ/thymeleaf/impl/ThymeleafTemplateEngineImpl.java
  vertx-template-engines/vertx-web-templ-thymeleaf/src/test/java/io/vertx/ext/web/templ/ThymeleafTemplateNoCacheTest.java
  vertx-template-engines/vertx-web-templ-thymeleaf/src/test/java/io/vertx/ext/web/templ/ThymeleafTemplateTest.java
  vertx-web-common/src/main/java/io/vertx/ext/web/common/WebEnvironment.java
  vertx-web-common/src/main/java/io/vertx/ext/web/common/template/CachingTemplateEngine.java
  vertx-web/src/main/java/io/vertx/ext/web/handler/ErrorHandler.java
  vertx-web/src/main/java/io/vertx/ext/web/handler/StaticHandler.java
  vertx-web/src/main/java/io/vertx/ext/web/handler/impl/StaticHandlerImpl.java
  vertx-web/src/main/java/io/vertx/ext/web/package-info.java
  vertx-web/src/main/java/io/vertx/ext/web/templ/CachingTemplateEngine.java
  vertx-web/src/test/java/io/vertx/ext/web/handler/ErrorHandlerTest.java
Labels: to review

#1183 Vert.x Web GraphQL
  pom.xml
  vertx-web-graphql/pom.xml
  vertx-web-graphql/src/main/asciidoc/dataobjects.adoc
  vertx-web-graphql/src/main/asciidoc/index.adoc
  vertx-web-graphql/src/main/generated/io/vertx/ext/web/handler/graphql/GraphQLHandlerOptionsConverter.java
  vertx-web-graphql/src/main/java/examples/GraphQLExamples.java
  vertx-web-graphql/src/main/java/examples/package-info.java
  vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/GraphQLHandler.java
  vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/GraphQLHandlerOptions.java
  vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/TriConsumer.java
  vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/VertxBatchLoader.java
  vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/VertxDataFetcher.java
  vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/VertxPropertyDataFetcher.java
  vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/impl/GraphQLBatch.java
  vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/impl/GraphQLHandlerImpl.java
  vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/impl/GraphQLInput.java
  vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/impl/GraphQLInputDeserializer.java
  vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/impl/GraphQLQuery.java
  vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/package-info.java
  vertx-web-graphql/src/test/java/io/vertx/ext/web/handler/graphql/BatchLoaderTest.java
  vertx-web-graphql/src/test/java/io/vertx/ext/web/handler/graphql/BatchRequestsTest.java
  vertx-web-graphql/src/test/java/io/vertx/ext/web/handler/graphql/GetRequestsTest.java
  vertx-web-graphql/src/test/java/io/vertx/ext/web/handler/graphql/GraphQLRequest.java
  vertx-web-graphql/src/test/java/io/vertx/ext/web/handler/graphql/GraphQLTestBase.java
  vertx-web-graphql/src/test/java/io/vertx/ext/web/handler/graphql/JsonResultsTest.java
  vertx-web-graphql/src/test/java/io/vertx/ext/web/handler/graphql/Link.java
  vertx-web-graphql/src/test/java/io/vertx/ext/web/handler/graphql/PostRequestsTest.java
  vertx-web-graphql/src/test/java/io/vertx/ext/web/handler/graphql/PostRequestsWithBodyHandlerTest.java
  vertx-web-graphql/src/test/java/io/vertx/ext/web/handler/graphql/QueryContextTest.java
  vertx-web-graphql/src/test/java/io/vertx/ext/web/handler/graphql/TestData.java
  vertx-web-graphql/src/test/java/io/vertx/ext/web/handler/graphql/UnsupportedMethodTest.java
  vertx-web-graphql/src/test/java/io/vertx/ext/web/handler/graphql/User.java
  vertx-web-graphql/src/test/java/io/vertx/ext/web/handler/graphql/VertxDataFetcherTest.java
  vertx-web-graphql/src/test/java/io/vertx/ext/web/handler/graphql/impl/GraphQLInputDeserializerTest.java
  vertx-web-graphql/src/test/resources/links.graphqls
Labels: in progress, to review

#1204 Not implemented no more mounted when method is not allowed
  vertx-web-api-contract/src/main/asciidoc/dataobjects.adoc
  vertx-web-api-contract/src/main/asciidoc/index.adoc
  vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/RouterFactoryOptions.java
  vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/openapi3/impl/OpenAPI3RouterFactoryImpl.java
  vertx-web-api-contract/src/test/java/io/vertx/ext/web/api/contract/openapi3/OpenAPI3RouterFactoryTest.java
  vertx-web-api-contract/src/test/resources/swaggers/router_factory_test.yaml
Labels: component/api-contract/bug

#1209 Fixes #1160
  vertx-web/src/main/java/io/vertx/ext/web/handler/impl/BodyHandlerImpl.java
Labels: to review

#1208 Documentation for the Rocker template engine
  vertx-web/src/main/asciidoc/index.adoc
Labels: documentation, to review

#1156 Merged the functionality of SessionHandler and UserSessionHandler as …
  vertx-web/src/main/java/examples/WebExamples.java
  vertx-web/src/main/java/io/vertx/ext/web/handler/SessionHandler.java
  vertx-web/src/main/java/io/vertx/ext/web/handler/UserSessionHandler.java
  vertx-web/src/main/java/io/vertx/ext/web/handler/impl/SessionHandlerImpl.java
  vertx-web/src/main/java/io/vertx/ext/web/handler/impl/UserSessionHandlerImpl.java
  vertx-web/src/test/java/io/vertx/ext/web/handler/BasicAuthHandlerTest.java
  vertx-web/src/test/java/io/vertx/ext/web/handler/RedirectAuthHandlerTest.java
Labels: enhancement
