Repository vert-x3/vertx-web, pull requests merged in 2019-01, with the labels that each got.

#1121 Fix #1120 - Add null check to handle when no encoding is provided for…
  vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/openapi3/impl/OpenAPI3RequestValidationHandlerImpl.java
Labels: to review

#1131 Solves regression from 3.5 semicolon in path
  vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/openapi3/impl/OpenAPI3PathResolver.java
  vertx-web-api-contract/src/test/java/io/vertx/ext/web/api/contract/openapi3/OpenAPI3PathResolverTest.java
  vertx-web-api-contract/src/test/resources/swaggers/path_resolver_test.yaml
Labels: component/api-contract/bug

#1141 Basic access and bearer token authentication mechanisms
  vertx-web-client/src/main/asciidoc/index.adoc
  vertx-web-client/src/main/java/examples/WebClientExamples.java
  vertx-web-client/src/main/java/io/vertx/ext/web/client/HttpRequest.java
  vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/HttpRequestImpl.java
  vertx-web-client/src/test/java/io/vertx/ext/web/client/WebClientTest.java
Labels: enhancement
