Repository vert-x3/vertx-web, pull requests merged in 2019-05, with the labels that each got.

#1256 digest auth: parse nonce count as hex
  vertx-web/src/main/java/io/vertx/ext/web/handler/impl/DigestAuthHandlerImpl.java
Labels: bug, to review

#1255 pebble: add extension to resolve JsonArray and JsonObject
  vertx-template-engines/vertx-web-templ-pebble/pom.xml
  vertx-template-engines/vertx-web-templ-pebble/src/main/java/io/vertx/ext/web/templ/pebble/impl/PebbleTemplateEngineImpl.java
  vertx-template-engines/vertx-web-templ-pebble/src/main/java/io/vertx/ext/web/templ/pebble/impl/PebbleVertxAttributeResolver.java
  vertx-template-engines/vertx-web-templ-pebble/src/main/java/io/vertx/ext/web/templ/pebble/impl/PebbleVertxExtension.java
  vertx-template-engines/vertx-web-templ-pebble/src/test/filesystemtemplates/test-pebble-template3.peb
  vertx-template-engines/vertx-web-templ-pebble/src/test/resources/somedir/test-pebble-template2.beb
  vertx-template-engines/vertx-web-templ-pebble/src/test/resources/somedir/test-pebble-template2.peb
Labels: enhancement, to review

#1245 Fixed getAcceptableContentType()
  vertx-web/src/main/java/io/vertx/ext/web/ParsedHeaderValues.java
  vertx-web/src/main/java/io/vertx/ext/web/impl/ParsableHeaderValuesContainer.java
  vertx-web/src/test/java/io/vertx/ext/web/RouterTest.java
Labels: bug, to review

#1242 Fixes issue #1123
  vertx-web/src/main/java/io/vertx/ext/web/handler/impl/StaticHandlerImpl.java
  vertx-web/src/test/java/io/vertx/ext/web/handler/StaticHandlerTest.java
Labels: in progress

#1239 Now AuthHandlerImpl correctly manages HttpStatusException
  vertx-web/src/main/java/io/vertx/ext/web/handler/impl/AuthHandlerImpl.java
  vertx-web/src/test/java/io/vertx/ext/web/handler/CustomAuthHandlerTest.java
Labels: to review

#1176 vertx-web 3.7 - fix potentials null pointer exception
  vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/validation/impl/ArrayTypeValidator.java
  vertx-web-api-service/src/main/java/io/vertx/ext/web/api/generator/impl/model/WebApiProxyModel.java
  vertx-web/src/main/java/io/vertx/ext/web/handler/impl/BodyHandlerImpl.java
  vertx-web/src/main/java/io/vertx/ext/web/handler/impl/StaticHandlerImpl.java
Labels: enhancement

#1115 fix:issues/1114
  vertx-web-client/src/main/java/io/vertx/ext/web/client/HttpRequest.java
  vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/HttpRequestImpl.java
  vertx-web-client/src/test/java/io/vertx/ext/web/client/WebClientTest.java
Labels: to review

#1262 Pebble: add a new test case ...
  vertx-template-engines/vertx-web-templ-pebble/src/main/java/io/vertx/ext/web/templ/pebble/impl/PebbleVertxExtension.java
  vertx-template-engines/vertx-web-templ-pebble/src/test/filesystemtemplates/test-pebble-template6.peb
  vertx-template-engines/vertx-web-templ-pebble/src/test/java/io/vertx/ext/web/templ/PebbleTemplateTest.java
Labels: to review

#1265 Removed unnecessary encoding of query params in web client
  vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/HttpContext.java
  vertx-web-client/src/test/java/io/vertx/ext/web/client/WebClientTest.java
Labels: to review

#1267 fix badge
  README.adoc
Labels: to review

#1259 Moved file-uploads directory to target
  vertx-web-api-contract/src/test/java/io/vertx/ext/web/api/contract/openapi3/OpenAPI3RouterFactoryTest.java
  vertx-web-api-contract/src/test/java/io/vertx/ext/web/api/validation/HTTPRequestValidationTest.java
  vertx-web-api-contract/src/test/java/io/vertx/ext/web/api/validation/WebTestValidationBase.java
Labels: to review

#1263 Lazy decoding of query parameters in RoutingContext
  vertx-web/src/main/java/io/vertx/ext/web/RoutingContext.java
  vertx-web/src/main/java/io/vertx/ext/web/impl/RouteImpl.java
  vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImpl.java
  vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImplBase.java
  vertx-web/src/test/java/io/vertx/ext/web/RouterTest.java
Labels: to review

#1248 Document development mode
  vertx-web/src/main/asciidoc/index.adoc
Labels: to review

#1261 Added getHttpMethods to Route interface
  vertx-web/src/main/java/io/vertx/ext/web/Route.java
  vertx-web/src/main/java/io/vertx/ext/web/impl/RouteImpl.java
Labels: enhancement, to review
