Repository vert-x3/vertx-web, pull requests merged in 2019-08, with the labels that each got.

#1346 Futurize web
  vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/openapi3/OpenAPI3RouterFactory.java
  vertx-web-client/src/main/java/io/vertx/ext/web/client/HttpRequest.java
  vertx-web-common/src/main/java/io/vertx/ext/web/common/template/TemplateEngine.java
  vertx-web/src/main/java/io/vertx/ext/web/handler/AuthHandler.java
  vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/SockJSSocket.java
  vertx-web/src/main/java/io/vertx/ext/web/sstore/SessionStore.java
Labels: enhancement

#996 Fixes #767
  vertx-web/src/main/java/io/vertx/ext/web/handler/JWTAuthHandler.java
  vertx-web/src/main/java/io/vertx/ext/web/handler/impl/JWTAuthHandlerImpl.java
Labels: to review

#1343 GraphiQL React app
  .travis.yml
  vertx-web-graphql/src/main/asciidoc/dataobjects.adoc
  vertx-web-graphql/src/main/asciidoc/index.adoc
  vertx-web-graphql/src/main/generated/io/vertx/ext/web/handler/graphql/GraphQLHandlerOptionsConverter.java
  vertx-web-graphql/src/main/generated/io/vertx/ext/web/handler/graphql/GraphiQLHandlerOptionsConverter.java
  vertx-web-graphql/src/main/java/examples/GraphQLExamples.java
  vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/GraphQLHandler.java
  vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/GraphQLHandlerOptions.java
  vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/GraphiQLHandler.java
  vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/GraphiQLHandlerOptions.java
  vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/impl/GraphQLHandlerImpl.java
  vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/impl/GraphiQLHandlerImpl.java
  vertx-web-graphql/src/main/resources/io/vertx/ext/web/handler/graphql/graphiql.html
  vertx-web-graphql/src/test/java/io/vertx/ext/web/handler/graphql/ApolloTestsServer.java
  vertx-web-graphql/vertx-web-graphiql/.gitignore
  vertx-web-graphql/vertx-web-graphiql/package-lock.json
  vertx-web-graphql/vertx-web-graphiql/package.json
  vertx-web-graphql/vertx-web-graphiql/public/index.html
  vertx-web-graphql/vertx-web-graphiql/src/index.css
  vertx-web-graphql/vertx-web-graphiql/src/index.js
Labels: graphql
