Repository vert-x3/vertx-web, pull requests merged in 2019-04, with the labels that each got.

#1216 digest auth: uri in authorization header must match request uri
  vertx-web/src/main/java/io/vertx/ext/web/handler/impl/DigestAuthHandlerImpl.java
Labels: to review

#1214 Fix issue #1213
  vertx-web-api-contract/src/main/asciidoc/index.adoc
  vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/openapi3/impl/OpenAPI3RequestValidationHandlerImpl.java
  vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/openapi3/impl/OpenApi3Utils.java
  vertx-web-api-contract/src/test/java/io/vertx/ext/web/api/ApiWebTestBase.java
  vertx-web-api-contract/src/test/java/io/vertx/ext/web/api/contract/openapi3/OpenAPI3RouterFactoryTest.java
  vertx-web-api-contract/src/test/java/io/vertx/ext/web/api/contract/openapi3/OpenAPI3ValidationTest.java
  vertx-web-api-contract/src/test/resources/random-file
  vertx-web-api-contract/src/test/resources/random.csv
  vertx-web-api-contract/src/test/resources/random.txt
  vertx-web-api-contract/src/test/resources/swaggers/multipart.yaml
  vertx-web-api-contract/src/test/resources/swaggers/validation_test.yaml
Labels: component/api-contract/bug

#1229 Raw SockJS transport should write text frame when sending a text mess…
  vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/RawWebSocketTransport.java
  vertx-web/src/test/java/io/vertx/ext/web/handler/sockjs/SockJSRawTransportTest.java
Labels: to review

#1215 Updated swagger-parser & json-schema-validator
  vertx-web-api-contract/pom.xml
Labels: component/api-contract/enhancement

#1220 EnumTypeValidator correctly accepts different types for allowedValues other than List<String>
  vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/openapi3/impl/OpenAPI3RequestValidationHandlerImpl.java
  vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/impl/RequestParameterImpl.java
  vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/validation/ParameterTypeValidator.java
  vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/validation/impl/EnumTypeValidator.java
  vertx-web-api-contract/src/test/java/io/vertx/ext/web/api/contract/openapi3/OpenAPI3ValidationTest.java
  vertx-web-api-contract/src/test/java/io/vertx/ext/web/api/validation/impl/EnumTypeValidatorTest.java
  vertx-web-api-contract/src/test/resources/swaggers/validation_test.yaml
Labels: component/api-contract/bug

#1233 Fixed binary data in web api service
  vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/contract/impl/RouteToEBServiceHandler.java
  vertx-web-api-service/src/test/java/io/vertx/ext/web/api/router_factory_integration/BinaryTestService.java
  vertx-web-api-service/src/test/java/io/vertx/ext/web/api/router_factory_integration/BinaryTestServiceImpl.java
  vertx-web-api-service/src/test/java/io/vertx/ext/web/api/router_factory_integration/OpenAPI3ServiceProxiesTest.java
  vertx-web-api-service/src/test/resources/swaggers/service_proxy_test.yaml
Labels: component/api-service/bug, to review

#1234 ValidationException now overrides getMessage
  vertx-web-api-contract/src/main/java/io/vertx/ext/web/api/validation/ValidationException.java
Labels: component/api-contract/bug

#1243 Added documentation for JWT auth
  vertx-web/src/main/asciidoc/index.adoc
Labels: to review

#1247 Expose GraphiQL for development
  vertx-web-graphql/src/main/asciidoc/dataobjects.adoc
  vertx-web-graphql/src/main/asciidoc/index.adoc
  vertx-web-graphql/src/main/generated/io/vertx/ext/web/handler/graphql/GraphQLHandlerOptionsConverter.java
  vertx-web-graphql/src/main/generated/io/vertx/ext/web/handler/graphql/GraphiQLOptionsConverter.java
  vertx-web-graphql/src/main/java/examples/GraphQLExamples.java
  vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/GraphQLHandler.java
  vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/GraphQLHandlerOptions.java
  vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/GraphiQLOptions.java
  vertx-web-graphql/src/main/java/io/vertx/ext/web/handler/graphql/impl/GraphQLHandlerImpl.java
  vertx-web-graphql/src/main/resources/io/vertx/ext/web/handler/graphql/graphiql.html
Labels: to review

#1250 Add warning to documentation about not reusing WebClient instance
  vertx-web-client/src/main/asciidoc/index.adoc
Labels: to review

#1244 Solved conflicts between SockJS and CORS handlers
  vertx-web/src/main/java/io/vertx/ext/web/handler/impl/CorsHandlerImpl.java
  vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/BaseTransport.java
  vertx-web/src/test/java/io/vertx/ext/web/handler/CORSHandlerTest.java
  vertx-web/src/test/java/io/vertx/ext/web/handler/sockjs/SockJSCORSTest.java
Labels: bug, to review

#1253 Fix wrong handling of error messages vertx-eventbus.js
  vertx-web/src/client/vertx-eventbus.js
Labels: bug, to review

#1240 CSRFHandler now safely calls Mac.doFinal
  vertx-web/src/main/java/io/vertx/ext/web/handler/impl/CSRFHandlerImpl.java
Labels: to review
