Repository vert-x3/vertx-web, pull requests merged in 2020-12, with the labels that each got.

#1802 Doc #1655
  vertx-web-openapi/src/main/asciidoc/index.adoc
  vertx-web-openapi/src/main/java/examples/OpenAPI3Examples.java
Labels: documentation

#1764 Allow parsing of query parameters with other content encoding than UTF-8
  vertx-web/src/main/java/io/vertx/ext/web/RoutingContext.java
  vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextDecorator.java
  vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextImpl.java
  vertx-web/src/main/java/io/vertx/ext/web/impl/RoutingContextWrapper.java
  vertx-web/src/test/java/io/vertx/ext/web/RouterTest.java
Labels: enhancement

#1809 Ensure that pause and resume are only called if the request isn't ended
  vertx-web/src/main/java/io/vertx/ext/web/handler/impl/AuthenticationHandlerImpl.java
  vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/RawWebSocketTransport.java
  vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/WebSocketTransport.java
Labels: bug

#1807 codegen related issues
  vertx-web-openapi/src/main/generated/io/vertx/ext/web/openapi/RouterBuilderOptionsConverter.java
  vertx-web-openapi/src/main/java/io/vertx/ext/web/openapi/ErrorType.java
  vertx-web-openapi/src/main/java/io/vertx/ext/web/openapi/RouteNamingStrategy.java
  vertx-web-openapi/src/main/java/io/vertx/ext/web/openapi/RouterBuilderException.java
  vertx-web-openapi/src/main/java/io/vertx/ext/web/openapi/RouterBuilderOptions.java
  vertx-web-openapi/src/main/java/io/vertx/ext/web/openapi/impl/ContractEndpointHandler.java
  vertx-web-openapi/src/main/java/io/vertx/ext/web/openapi/package-info.java
  vertx-web-openapi/src/test/java/io/vertx/ext/web/openapi/RouterBuilderIntegrationTest.java
  vertx-web-openapi/src/test/java/io/vertx/ext/web/openapi/RouterBuilderSecurityTest.java
  vertx-web-session-stores/vertx-web-sstore-cookie/src/main/java/io/vertx/ext/web/sstore/cookie/package-info.java
  vertx-web-session-stores/vertx-web-sstore-redis/src/main/java/io/vertx/ext/web/sstore/redis/package-info.java
Labels: bug

#1815 Fix NPE when sending JSON data and the user agent header is disabled
  vertx-web-client/src/main/java/io/vertx/ext/web/client/impl/HttpRequestImpl.java
  vertx-web-client/src/test/java/io/vertx/ext/web/client/WebClientTest.java
Labels: bug

#1823 Lower the verbosity of log (from error to debug) when head written si…
  vertx-web/src/main/java/io/vertx/ext/web/handler/impl/ErrorHandlerImpl.java
Labels: enhancement
