Repository vert-x3/vertx-web, pull requests merged in 2020-10, with the labels that each got.

#1713 Always read resources with FS
  vertx-web/src/main/java/examples/WebExamples.java
  vertx-web/src/main/java/io/vertx/ext/web/handler/ErrorHandler.java
  vertx-web/src/main/java/io/vertx/ext/web/handler/FaviconHandler.java
  vertx-web/src/main/java/io/vertx/ext/web/handler/impl/ErrorHandlerImpl.java
  vertx-web/src/main/java/io/vertx/ext/web/handler/impl/FaviconHandlerImpl.java
  vertx-web/src/main/java/io/vertx/ext/web/handler/impl/StaticHandlerImpl.java
  vertx-web/src/main/java/io/vertx/ext/web/handler/impl/UserHolder.java
  vertx-web/src/main/java/io/vertx/ext/web/impl/Utils.java
  vertx-web/src/main/java/io/vertx/ext/web/sstore/impl/SharedDataSessionImpl.java
  vertx-web/src/test/java/io/vertx/ext/web/handler/ErrorHandlerTest.java
  vertx-web/src/test/java/io/vertx/ext/web/handler/FaviconHandlerTest.java
  vertx-web/src/test/java/io/vertx/ext/web/handler/StaticHandlerTest.java
  vertx-web/src/test/java/io/vertx/ext/web/handler/sockjs/SockJSWriteHandlerTestServer.java
  vertx-web/src/test/java/io/vertx/ext/web/templ/TemplateTest.java
Labels: enhancement

#1724 Detect race on close of sockjs tests
  vertx-template-engines/vertx-web-templ-pebble/src/main/java/io/vertx/ext/web/templ/pebble/PebbleTemplateEngine.java
  vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/SockJSSession.java
  vertx-web/src/test/java/io/vertx/ext/web/WebTestBase.java
Labels: bug

#1727 Fixes #1411
  vertx-web/src/main/asciidoc/index.adoc
  vertx-web/src/main/java/io/vertx/ext/web/impl/RouteState.java
  vertx-web/src/test/java/io/vertx/ext/web/RouterTest.java
Labels: enhancement

#1731 Fix #1730: properly extract the rest param as the desired segment
  vertx-web/src/main/java/io/vertx/ext/web/impl/Utils.java
  vertx-web/src/test/java/io/vertx/ext/web/templ/TemplateTest.java
Labels: bug

#1734 Implement the openapi endpoint
  vertx-web-openapi/src/main/asciidoc/dataobjects.adoc
  vertx-web-openapi/src/main/generated/io/vertx/ext/web/openapi/RouterFactoryOptionsConverter.java
  vertx-web-openapi/src/main/java/io/vertx/ext/web/openapi/RouterFactoryOptions.java
  vertx-web-openapi/src/main/java/io/vertx/ext/web/openapi/impl/ContractEndpointHandler.java
  vertx-web-openapi/src/main/java/io/vertx/ext/web/openapi/impl/OpenAPI3RouterFactoryImpl.java
  vertx-web-openapi/src/test/java/io/vertx/ext/web/openapi/RouterFactoryIntegrationTest.java
  vertx-web-validation/src/test/java/io/vertx/ext/web/validation/testutils/TestRequest.java
Labels: component/openapi, enhancement

#1735 Fixed wrong usage of vertx junit5 apis
  vertx-web-openapi/src/test/java/io/vertx/ext/web/openapi/BaseRouterFactoryTest.java
  vertx-web-validation/src/test/java/io/vertx/ext/web/validation/BaseValidationHandlerTest.java
Labels: bug, component/openapi

#1749 Bump to the latest stable sockjs 1.5.0
  vertx-web-client/src/main/asciidoc/dataobjects.adoc
  vertx-web/src/test/sockjs-protocol/sockjs-protocol.py
  vertx-web/src/test/sockjs-protocol/websocket.py
  vertx-web/src/test/sockjs-protocol/websocket/__init__.py
  vertx-web/src/test/sockjs-protocol/websocket/_abnf.py
  vertx-web/src/test/sockjs-protocol/websocket/_app.py
  vertx-web/src/test/sockjs-protocol/websocket/_cookiejar.py
  vertx-web/src/test/sockjs-protocol/websocket/_core.py
  vertx-web/src/test/sockjs-protocol/websocket/_exceptions.py
  vertx-web/src/test/sockjs-protocol/websocket/_handshake.py
  vertx-web/src/test/sockjs-protocol/websocket/_http.py
  vertx-web/src/test/sockjs-protocol/websocket/_logging.py
  vertx-web/src/test/sockjs-protocol/websocket/_socket.py
  vertx-web/src/test/sockjs-protocol/websocket/_ssl_compat.py
  vertx-web/src/test/sockjs-protocol/websocket/_url.py
  vertx-web/src/test/sockjs-protocol/websocket/_utils.py
  vertx-web/src/test/sockjs-protocol/websocket/tests/__init__.py
  vertx-web/src/test/sockjs-protocol/websocket/tests/data/header01.txt
  vertx-web/src/test/sockjs-protocol/websocket/tests/data/header02.txt
  vertx-web/src/test/sockjs-protocol/websocket/tests/test_cookiejar.py
  vertx-web/src/test/sockjs-protocol/websocket/tests/test_websocket.py
Labels: enhancement

#1754 change validation of incorrect basic auth to respond with 400 malformed request
  vertx-web/src/main/java/io/vertx/ext/web/handler/impl/BasicAuthHandlerImpl.java
  vertx-web/src/test/java/io/vertx/ext/web/handler/BasicAuthHandlerTest.java
Labels: bug

#1759 Fixed Internal server error on displayExceptionDetails = true and exc…
  vertx-web/src/main/java/io/vertx/ext/web/handler/impl/ErrorHandlerImpl.java
  vertx-web/src/test/java/io/vertx/ext/web/handler/ErrorHandlerTest.java
Labels: bug
