Repository vert-x3/vertx-web, pull requests merged in 2021-03, with the labels that each got.

#1816 Schema#getDefaultValue() throws NoSyncValidationException if it is a RefSchema
  vertx-web-validation/src/main/java/io/vertx/ext/web/validation/impl/parameter/ParameterProcessorImpl.java
  vertx-web-validation/src/main/java/io/vertx/ext/web/validation/impl/validator/SchemaValidator.java
  vertx-web-validation/src/main/java/io/vertx/ext/web/validation/impl/validator/ValueValidator.java
  vertx-web-validation/src/test/java/io/vertx/ext/web/validation/impl/ParameterProcessorUnitTest.java
Labels: bug, component/openapi

#1882 vertx-web-api-service now it's optional for vertx-web-openapi
  vertx-web-openapi/pom.xml
  vertx-web-openapi/src/main/java/io/vertx/ext/web/openapi/impl/OpenAPI3RouterBuilderImpl.java
  vertx-web-openapi/src/main/java/io/vertx/ext/web/openapi/impl/OpenAPI3Utils.java
Labels: component/openapi, enhancement

#1894 feat: Add LoggerFormatter to LoggerHandler
  vertx-web/src/main/java/io/vertx/ext/web/handler/LoggerFormatter.java
  vertx-web/src/main/java/io/vertx/ext/web/handler/LoggerHandler.java
  vertx-web/src/main/java/io/vertx/ext/web/handler/impl/LoggerHandlerImpl.java
  vertx-web/src/test/java/io/vertx/ext/web/handler/LoggerHandlerTest.java
Labels: enhancement

#1885 Fix broken schema normalization
  vertx-web-openapi/src/main/java/io/vertx/ext/web/openapi/RouterBuilder.java
  vertx-web-openapi/src/main/java/io/vertx/ext/web/openapi/RouterBuilderException.java
  vertx-web-openapi/src/main/java/io/vertx/ext/web/openapi/impl/OpenAPI3PathResolver.java
  vertx-web-openapi/src/main/java/io/vertx/ext/web/openapi/impl/OpenAPI3Utils.java
  vertx-web-openapi/src/main/java/io/vertx/ext/web/openapi/impl/OpenAPIHolderImpl.java
  vertx-web-openapi/src/test/java/io/vertx/ext/web/openapi/RouterBuilderIntegrationTest.java
  vertx-web-openapi/src/test/resources/specs/repro_1876.yaml
  vertx-web-validation/src/test/java/io/vertx/ext/web/validation/testutils/JsonSchemaValidatorExtension.java
Labels: bug, component/openapi

#1902 JSON content type should follow IANA registry rules
  vertx-web/src/main/java/io/vertx/ext/web/RoutingContext.java
  vertx-web/src/test/java/io/vertx/ext/web/RouterTest.java
  vertx-web/src/test/java/io/vertx/ext/web/impl/RoutingContextImplTest.java
  vertx-web/src/test/java/io/vertx/ext/web/it/RoutingContextDatabindTest.java
Labels: enhancement
