Repository vert-x3/vertx-web, pull requests merged in 2021-05, with the labels that each got.

#1940 Fix #1873
  vertx-web-openapi/src/main/java/io/vertx/ext/web/openapi/impl/OpenAPIHolderImpl.java
  vertx-web-openapi/src/test/java/io/vertx/ext/web/openapi/impl/OpenAPIHolderTest.java
  vertx-web-openapi/src/test/resources/local_refs_in_jar.yaml
Labels: bug

#1945 Fix #1933
  vertx-web/src/main/java/io/vertx/ext/web/impl/Origin.java
  vertx-web/src/test/java/io/vertx/ext/web/handler/CORSHandlerTest.java
  vertx-web/src/test/java/io/vertx/ext/web/impl/OriginTest.java
Labels: enhancement

#1947 Add cookie attributes also when expiring
  vertx-web/src/main/java/io/vertx/ext/web/handler/impl/SessionHandlerImpl.java
  vertx-web/src/test/java/io/vertx/ext/web/handler/SessionHandlerTestBase.java
Labels: bug

#1953 Fix regex for multipart encoding
  vertx-web-openapi/src/main/java/io/vertx/ext/web/openapi/impl/OpenAPI3Utils.java
  vertx-web-openapi/src/test/java/io/vertx/ext/web/openapi/RouterBuilderIntegrationTest.java
  vertx-web-openapi/src/test/resources/specs/multipart.yaml
Labels: bug, component/openapi
